### ISSUE TITLE
Conferma password in creazione account non necessaria

### ISSUE THREAD

**Issue by Nick87** [tomorrowdevs-projects/dashboard-issues#12]
La password di conferma (`password2` nel request body) nella POST `https://api.tomorrowdevs.com/auth/register` potrebbe non essere necessaria: è sufficiente un check FE del fatto che coincidano

**Comment by storrisi** [comment]
Un controllo lato FE non garantirebbe integrità delle operazioni lato backend, è sempre meglio proteggere entrambe

**Comment by Nick87** [comment]
Ma l'integrità della password si verifica con l'unico campo password che arriva: per cultura personale, a che può giovare avere entrambe a BE? Io pensavo che avere il doppio campo serva soltanto ad essere sicuri che l'utente è cosciente della password che ha inserito, e basta solo un check FE per questo
