### ISSUE TITLE
Il cursore indica l'azione sbagliata sul bottone "candidature aperte" e il verde è troppo chiaro con la scritta bianca

### ISSUE THREAD

**Issue by alessandrooppe** [tomorrowdevs-projects/dashboard-issues#17]

**Comment by storrisi** [comment]
@alessandrooppe potresti fornire maggiori dettagli riguardo la segnalazione? A quale azione sbagliata ti riferisci?

**Comment by MaurizioAba** [comment]
I'll try to answer, basically what you are indicating for button click action is the cursor text (wrong). Instead it should be changed to cursor pointer

**Comment by alessandrooppe** [comment]
Yes the problem is the type of coursor, in /projects pgae on "Candidature Aperte"

**Comment by tomorrowdevsit** [comment]
Mentioned in #48
