### ISSUE TITLE
Zero Knowledge Learn the basics of programming end of video intro to programming

### ISSUE THREAD

**Issue by MaurizioAba** [tomorrowdevs-projects/dashboard-issues#24]
After having watched the entire video of the first lesson, at the end of the video, before clicking on the icon indicating that I have finished watching, I opened the console which tells me:

Request failed with status code 500
code: 'ERR_BAD_RESPONSE

How to reproduce

<img width="690" alt="Zero Knowledge Learning Path_start_of_lesson" src="https://github.com/user-attachments/assets/58366d94-0d1a-4573-b2ec-7efe338b2758">

> 
</br>
</br>
</br>

 <img width="1660" alt="end-video-intro-prog" src="https://github.com/user-attachments/assets/40a9294f-94c1-4d1f-a2f4-b070f8efcb11">

**Comment by storrisi** [comment]
It should be fixed now, probably you would encounter some issues while trying again
