### ISSUE TITLE
Progress not saved after watching the first lesson - Capitolo 1  Introduzione alla Programmazione

### ISSUE THREAD

**Issue by MaurizioAba** [tomorrowdevs-projects/dashboard-issues#25]
Progress not saved: After watching the first lesson in its entirety, the corresponding icon showing a success dialog.
The card on the side is not updated and "Your progress" is shown: 0%

I clicked on the home button, then went back to the lessons page, and the progress is not saved and neither is the percentage of the progress card

<img width="1109" alt="lesson_one_ok_progress_no" src="https://github.com/user-attachments/assets/d6f3e226-6a1e-40b9-bd49-ba78f638e59b">

**Comment by storrisi** [comment]
It should be fixed now, probably you would encounter some issues while trying again
