### ISSUE TITLE
Home - Card activate the Premium plan

### ISSUE THREAD

**Issue by MaurizioAba** [tomorrowdevs-projects/dashboard-issues#26]
Homepage if I want to activate the premium plan and unlock all the routes etc when I click on the "activate it" button nothing happens.

<img width="331" alt="ActivePremium" src="https://github.com/user-attachments/assets/bf8e1570-04cb-4382-b74c-9203d71e475b">

**Comment by storrisi** [comment]
Segnalato anche nella #1

**Comment by storrisi** [comment]
Chiudo in quanto duplicata
