### ISSUE TITLE
Subscription e pagamento

### ISSUE THREAD

**Issue by JessFe** [tomorrowdevs-projects/dashboard-issues#27]
Processo subscription e pagamento

- Corso "Programming Basics", clicco "play"
- Scelgo un linguaggio tra JavaScript e Python

- **Step extra o vuoto:** Compare il nome del corso ed il pulsante "Inizia Percorso".
Sembra uno step di troppo, risulta scomodo.
Valuterei di aggiungere il linguaggio selezionato (tra il titolo ed il pulsante) per confermarlo, con magari un pulsante per tornare allo step precedente e cambiare scelta, oppure eliminare completamente questo step.
![image](https://github.com/user-attachments/assets/19ad2d37-40d5-4788-a5fc-699836a359bd)

- **Mentor o non mentor**: Non è chiaro cosa possa comportare questa scelta in termini di costi
![image](https://github.com/user-attachments/assets/c9a36cdd-ee35-4c2f-a334-116154115f84)

- **Prezzo abbonamento:** Sia che si scelga l'opzione mentor sia l'altra, qui non cambia nulla sulla base della scelta precedente.
Inoltre questo step occupa l'intera pagina, l'allineamento è completamente a sinistra.
![image](https://github.com/user-attachments/assets/f26e35f7-d512-43e2-8c69-73bdba39a7a1)

  Ideale sarebbe dargli l'aspetto che ha dal percorso ingranaggio > pulsante "Passa a Membership Premium"
  ![image](https://github.com/user-attachments/assets/8883fbf0-9d70-430b-ae88-c8a32875e178)

- **Prezzo in Stripe:** Cliccando "attiva subito" mi porta al pagamento, che in entrambi i casi (mentor o non mentor) risulta essere di 79€ (?)
![image](https://github.com/user-attachments/assets/24376df3-d7a3-431c-a04e-6c95129c69b3)

- **Checkout bianco:** Inserisco i dati della carta, clicco per confermare il pagamento, pagina bianca
(come già segnalato qui:  #16)
![image](https://github.com/user-attachments/assets/4b96de19-9cb6-4fa0-9e0c-33495bf9bb97)

**Comment by storrisi** [comment]
@JessFe ma poi dopo essere atterrata sul checkout, seppur pagina bianca, succede qualcosa?

**Comment by storrisi** [comment]
Giusto un chiarimento sui prezzi: al momento sono dei placeholder, non farci troppo caso

**Comment by JessFe** [comment]
> @JessFe ma poi dopo essere atterrata sul checkout, seppur pagina bianca, succede qualcosa?

Versione breve: ora il problema della pagina bianca è risolto, e il corso si sblocca correttamente.

Dettaglio: Ho ripetuto l'intero processo, ora dopo aver confermato i dati per il pagamento mostra una pagina di ringraziamento e mi avvisa che sarò reindirizzata. Quindi mi riporta a /path, il corso è sbloccato, e ho un messaggio di notifica (busta in alto a dx) che conferma la sottoscrizione dell'abbonamento con data e ora.
