### ISSUE TITLE
bottone "Consulta tutti i percorsi" 

### ISSUE THREAD

**Issue by aless10** [tomorrowdevs-projects/dashboard-issues#30]
In homepage, se vengono visualizzati tutti i percorsi (perche' al momento sono 2) il bottone "Consulta tutti i percorsi e' ridondante). Non so quanti percorsi/progetti si vogliono visualizzare in anteprima, ma se tutti sono gia' visibili allora il bottone non lo farei vedere.

![image](https://github.com/user-attachments/assets/e03a47cc-d6aa-4b4e-a858-bcca91c7cb00)

**Comment by storrisi** [comment]
Al momento questo sembra essere un bug vista la quantità di percorsi limitati, ma a regime non dovrebbe essere un problema
