### ISSUE TITLE
limite 3 ambiti in fase di profilazione non rispettato

### ISSUE THREAD

**Issue by aless10** [tomorrowdevs-projects/dashboard-issues#32]
Il limite di 3 sugli ambiti non e' rispettato

![image](https://github.com/user-attachments/assets/efda9df0-4479-4552-b436-400bb7f0dd28)

nel test ho selezionato tutte le opzioni e sono andato avanti e non mi ha dato errore o avviso.

**Comment by MaurizioAba** [comment]
Hi, already reported and opened see #13

**Comment by storrisi** [comment]
Duplicate of #13
