### ISSUE TITLE
Homepage - Blank and empty cards (Skeleton component)

### ISSUE THREAD

**Issue by MaurizioAba** [tomorrowdevs-projects/dashboard-issues#39]
When the site is unreachable (network error) on the homepage where it fails to load elements, I see empty empty cards. Would a suggestion be to insert static placeholders?

<img width="691" alt="Placeholder" src="https://github.com/user-attachments/assets/5fe05842-52b3-4646-9578-f9a7823637e6">

**Comment by tomorrowdevsit** [comment]
These are placeholder skeleton used from the UI Library, Material UI.

There could be room for a discussion here, but for now this won't change

**Comment by MaurizioAba** [comment]
Ok, sure.
