### ISSUE TITLE
La modale di lezione completata è scrollabile anche quando non necessario.

### ISSUE THREAD

**Issue by tomorrowdevsit** [tomorrowdevs-projects/dashboard-issues#53]

**Comment by tomorrowdevsit** [comment]
Per replicare: completa una lezione di un corso qualsiasi.  
Verrà aperta una modale con un'animazione di completamento.

**Comment by pinnetta** [comment]
> Per replicare: completa una lezione di un corso qualsiasi. Verrà aperta una modale con un'animazione di completamento.

Ho seguito le istruzioni per replicare il bug, ma non sono ricapitata nella stessa casistica. Il problema non riesco a replicarlo

**Comment by storrisi** [comment]
Grazie @pinnetta , per il momento chiudiamo, se si dovesse ripresentare valuteremo
