### ISSUE TITLE
Login popup occupa tutta l'altezza disponibile

### ISSUE THREAD

**Issue by NicolaLC** [tomorrowdevs-projects/dashboard-issues#7]
![image](https://github.com/user-attachments/assets/55b52515-974d-4735-accd-9616b42d347e)

Come si nota dallo screenshot il form di login occupa tutto lo spazio verticale, ne risultano spazi vuoti troppo ampi.

## Browser
| Attribute     | Value                                                                                       |
|---------------|---------------------------------------------------------------------------------------------|
| Google Chrome | 127.0.6533.88 (Official Build) (64-bit)                                                     |
| Revision      | a2d0cb026721e4644e489b8ebb07038ca4e4351c-refs/branch-heads/6533@{#1846}                     |
| OS            | Linux                                                                                       |
| JavaScript    | V8 12.7.224.16                                                                              |
| User Agent    | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 |

**Comment by storrisi** [comment]
Fixato, grazie
